### PR TITLE
Fetch upstream (closes: #19, #20, #21)

### LINKED ISSUE #19: Frame opzetten (server-logica)
Express-server met routing etc

### LINKED ISSUE #20: Database-connectie maken
MongoDB Atlas doen?

### LINKED ISSUE #21: Inlogformulier maken
Inlog/registratie

### PR DESCRIPTION
**Pull request by DanielvandeVelde**
Pull all (new) files from my repository.    
No work will be lost since I believe a (better) copy of this main-branch is up on [refactor/modules](https://github.com/deannabosschert/Matcher/tree/refactor/modules) 

We could then start working in branches from this basic set-up.

### CODE REVIEW

**Review by deannabosschert — APPROVED** [review]
Looks very good to me!
Thanks for merging the two readme-structures beforehand to avoid conflicts later on.

Only thing left to do now would be passing on the correct .env data, right?

**Comment by deannabosschert** [comment]
I'm not a big fan of the semicolons in JavaScript though `;`, what is @ReiniervanLimpt  's preference on this?

**Comment by DanielvandeVelde** [comment]
> 
> 
> I'm not a big fan of the semicolons in JavaScript though `;`, what is @ReiniervanLimpt 's preference on this?

Should we make a different issue for the semicolons?  
We can keep them in now and create an issue for a wiki page: 'coding standards'/'code conventions' where we can discuss camelCase, arrow functions etc.

**Comment by DanielvandeVelde** [comment]
>
> 
> Only thing left to do now would be passing on the correct .env data, right?

Yes, I ofcourse created an `.env-example`-file but with us working together it might be smart to make sure we're all on the same database.  
I'll drop that information in our private Teams group 😃

**Comment by DanielvandeVelde** [comment]
I also quickly mentioned which Issues can already be closed by this PR.  
These are basic ones, others can be closed too but we will need to do some minor work to do so.  
(Like copying parts of my repo's wiki to this one)
Mentioned issues this PR closes are: #19, #20, #21

**Review by ReiniervanLimpt — APPROVED** [review]
Looks fine to me! i agree with deanna on the semicollons, we can talk about some code conventions if needed before i start on the AJAX integration.

**Pull request closed without merging**
