### PR TITLE
Feat/pwa

### PR DESCRIPTION
**Pull request by DanielvandeVelde**
Setting up PWA.  

Close to being done, just wanted to open this so we could talk about the (fav)icon.  
I also added some compression 😄 

closes #31

### CODE REVIEW

**Review by deannabosschert — CHANGES_REQUESTED** [review]
again; thx for removing the semicolons!

I would love to see the different functions in modules, can that be done?
Then I'll merge it right away :)

**Comment by DanielvandeVelde** [comment]
> again; thx for removing the semicolons!    

No problem 😄 

> I would love to see the different functions in modules, can that be done?

Sure, but which code or file specifically?   
If you mean all the code, we can make a new issue for that since that might be too large to fit in the PWA feature.

**Comment by ReiniervanLimpt** [comment]
> I would love to see the different functions in modules, can that be done?

If you mean splitting up the authController file into smaller chunks i can agree with that, i think the current structure is fine as it is but we could consider splitting up the authController file intro 3 files being:

- everything related to a users profile, like registering and managine profiles
-  liking users and showing matches
- logging in / logging out

I think this would be the most straight forward way as i see youve made a distinction between these functions in [the router file](https://github.com/deannabosschert/Matcher/blob/main/router/index.js) already by seperating those.

Other than that, looks fine to me!

**Review by ReiniervanLimpt — APPROVED** [review]
Approved! but lets decide on whether we want to split up some files into smaller modules before merging.

**Review by deannabosschert — APPROVED** [review]
thought this was already included in the last one, but nevertheless all good!

**Comment by deannabosschert** [comment]
Whooooop!!

giphy party

**Pull request merged**
